from Identificacion.fun import busqueda_valores_ausentes
from Identificacion.fun import info_valoresAusentes
from Identificacion.fun import Info_objetos_a_numericos
from Identificacion.fun import busqueda_variables_bool_y_categoricas
from Identificacion.fun import outliers
from Identificacion.fun import patrones_columnas
from Identificacion.fun import fecha
from Identificacion.fun import variable_constante
from Identificacion.fun import score_dq
